### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Maciek99** [ClipsAI/demo#1]
After installing required packages using "npm install" and running "npm run dev", this error appears in the console

⨯ RangeError: Maximum call stack size exceeded
    at useResizer (./src/hooks/resizer.ts:17:76)
    at useVideo (./src/hooks/video.ts:21:103)
    at useTrimmer (./src/hooks/trimmer.ts:33:105)
    at useVideo (./src/hooks/video.ts:22:102)
    at useTrimmer (./src/hooks/trimmer.ts:33:105)
    at useVideo (./src/hooks/video.ts:22:102)
    at useTrimmer (./src/hooks/trimmer.ts:33:105)
    ...

**Comment by armeltalla** [comment]
Hi! I'm so sorry, I still have not finished. It will be done by Wednesday or Thursday.

**Comment by armeltalla** [comment]
Please pull the updates and try again now!

**Comment by Maciek99** [comment]
It works now!
